KIKI-FPT/kiki

- BE/modules/Product/Product.js
Xong phần Create product api
ref: DTNF-3
>  feat: be-create-model-product-api

- FE/src/app/component/stack/header/sub-header.component.tsx
- FE/src/app/component/stack/header/vocher-header.component.tsx
tôi đã làm xong componet sub-header và vorcher header refs:DTNF-11
> style:create-componet-sub-hearder-and-vocher-header

- BE/config/configImage.js
tôi đã làm xong config image go up cloudinary
refs:DTNF-9
> feat:config-image-go-up-cloudinary

- BE/modules/Product/Service/Product.js
refs:DTNF-5
tôi đã bug xong create-get-one-api-product
> bug:create-get-one-api-product

- FE/src/app/component/parts/button/button.component.tsx
- FE/src/app/component/parts/input/input.component.tsx
tôi đã lm xong component input và button
refs: DTNF-10
> style :create-component-input-and-button-componet-reuse

- FE/src/app/component/parts/input/input.component.tsx
- FE/src/app/component/stack/header/header.component.tsx
- FE/src/app/component/stack/header/sub-header.component.tsx
- FE/src/app/component/stack/header/vocher-header.component.tsx
- FE/src/app/container/default-home/default-home.component.tsx
tôi đã làm xong componet Header
refs:DTNF-13
> style:create-component-header

- BE/modules/Product/Controller/Api/deleteProduct.js
- BE/modules/Product/Controller/index.js
- BE/modules/Product/Service/Product.js
- BE/routers/product.js
Tôi đã fix xong phần create-delete-api-product
ref:DTNF-6
> bug:be-create-delete-api-product

- BE/config/configImage.js
Tôi đã fix bug xong update image
refs:DTNF-9
> bug:config-image-go-up-cloudinary

- BE/modules/Product/Controller/Api/addProduct.js
- BE/modules/Product/Controller/index.js
- BE/modules/Product/Service/Product.js
- BE/routers/product.js
tôi đã fix bug xong chức năng addProduct
refs:DTNF-8
> bug:create-post-api-product

- BE/modules/Product/Model/Product.js
- BE/modules/Product/Service/Product.js
chỉnh lại phẩn create product API
ref: DTNF-3
> bug: be-create-model-product-api

- BE/modules/Product/Controller/Api/updateroduct.js
- BE/modules/Product/Controller/index.js
- BE/modules/Product/Service/Product.js
- BE/routers/product.js
Hoàn thành phần create api product update
ref: DTNF-7
> feat: be-create-update-api-product

- BE/routers/product.js
Tôi đã fix xong phần  create-delete-api-product 
ref:DTNF-6
> bug:be-create-delete-api-product 

- FE/src/app/component/parts/input/input.component.tsx
- FE/src/app/component/stack/header/header.component.tsx
- FE/src/app/component/stack/header/sub-header.component.tsx
- FE/src/app/component/stack/header/vocher-header.component.tsx
- FE/src/app/container/default-home/default-home.component.tsx
tôi đã reponesive xong component header
refs:DTNF-14
> style:reponsive-component-header

- BE/modules/Product/Service/Product.js
Chỉnh lại phần create api update product
ref: DTNF-7
> bug:be-create-update-api-product

- BE/modules/Category/Model/Category.js
Hoàn thành xong phần create Model api category
ref: DTNF-17
> feat: be-create-model-api-category

- BE/modules/Category/Controller/Api/getAllCategory.js
- BE/modules/Category/Controller/index.js
- BE/modules/Category/Service/Category.js
- BE/routers/category.js
- BE/routers/router.js
Hoàn thành phần create getAll api category
ref: DTNF-18
> feat:be-create-api-get-all-category

- FE/package-lock.json
- FE/package.json
- FE/src/app/component/parts/itemproduct/itemproduct.component.tsx
- FE/src/app/component/parts/rating/star.component.tsx
- FE/src/app/component/stack/swiper-list/swiper-list.component.tsx
- FE/src/app/modules/client/home/home.component.tsx
- FE/src/app/modules/client/home/main-home/component/collection/collection.component.tsx
- FE/src/app/modules/client/home/main-home/component/featured-category/featured-category.component.tsx
- FE/src/app/modules/client/home/main-home/component/list-product/list-product.component.tsx
- FE/src/app/modules/client/home/main-home/component/slice/slice.component.tsx
- FE/src/app/modules/client/home/main-home/component/understand/understand.component.tsx
- FE/src/app/modules/client/home/main-home/main-home.component.tsx
- FE/src/app/modules/client/home/sidebar-home/sidebar-home.component.tsx
tôi đã làm xog component ui home của client
refs:DTNF-15
> style:create-component-ui-home-page-of-the-client

- BE/modules/Category/Controller/Api/getOneCategory.js
- BE/modules/Category/Controller/index.js
- BE/modules/Category/Service/Category.js
- BE/routers/category.js
Tôi đã làm xong chức năng getOnecategory
refs:DTNF-19
> feat:be-create-api-get-one-category

- FE/src/app/component/parts/itemproduct/itemproduct.component.tsx
- FE/src/app/modules/client/home/main-home/main-home.component.tsx
- FE/src/app/modules/client/home/sidebar-home/sidebar-home.component.tsx
tôi đã tạo thêm các hove cho itemproduct và position sticky
> style:create more applications for the home page

- BE/modules/Category/Controller/Api/deleteCategory.js
- BE/modules/Category/Controller/index.js
- BE/modules/Category/Service/Category.js
- BE/routers/category.js
Hoàn thành phần create api delete category
Chỉnh lại phần getAll
ref: DTNF-20
> feat:be-create-api-delete-category

- BE/modules/Category/Controller/Api/addCategory.js
- BE/modules/Category/Controller/index.js
- BE/modules/Category/Service/Category.js
- BE/routers/category.js
refs:DTNF-21
tôi đã làm xong phần create-api-post-category
> feat:DTNF-21-be-create-api-post-category

- BE/modules/Category/Controller/Api/updateCategory.js
- BE/modules/Category/Controller/index.js
- BE/modules/Category/Service/Category.js
- BE/routers/category.js
Tôi đã làm xong phần updateCategory và đổi lại tên phần getOneCategory cho đúng quy chuẩn. refs:DTNF-22
> feat:be-create-api-update-category

- FE/src/app/component/stack/footer/footer.component.tsx
Tôi đã chỉnh lại một số lỗi của footer
> bug:footer

- BE/modules/Auth/Controller/Api/register.js
- BE/modules/Auth/Controller/index.js
- BE/modules/Auth/Model/Auth.js
- BE/modules/Auth/service/Auth.js
- BE/routers/auth.js
- BE/routers/router.js
Làm xong chức năng đăng kí
refs:DTNF-25
> feat:be-create-api-register

- BE/modules/Color/Controller/Api/addColor.js
- BE/modules/Color/Controller/index.js
- BE/modules/Color/Service/Color.js
- BE/routers/color.js
- BE/routers/router.js
Tôi đã làm xong api add color
refs:DTNF-29
> feat:create-api-add-color

- BE/middlewares/authorization.js
t đã làm xong phần check middlewares
refs: DTNF-27
> feact: DTNF-27-be-create-middlewares

- BE/modules/Cart/Model/Cart.js
Tôi đã làm xong model cart
refs:DTNF-30
> feat:DTNF-30-be-create-model-api-carts

- BE/modules/Cart/Controller/Api/deleteCart.js
- BE/modules/Cart/Controller/index.js
- BE/modules/Cart/Service/Cart.js
- BE/routers/cart.js
- BE/routers/router.js
Hoàn thành create api delete carts
ref: DTNF-32
> feat: be-create-api-delete-carts

- BE/modules/Order/Model/Order.js
tôi đã làm xong aoi model order
refs:DTNF-35
> feat:be-create-api-model-order

- FE/src/app/component/stack/footer/footer.component.tsx
Tôi đã làm xong responsive footer
refs: DTNF-38
> styte:fe-reponesive-ui-footer

- FE/src/app/component/stack/swiper-list/swiper-list.component.tsx
- FE/src/app/hook/useWindow.ts
- FE/src/app/modules/client/home/home.component.tsx
- FE/src/app/modules/client/home/main-home/component/list-product/list-product.component.tsx
- FE/src/app/modules/client/home/main-home/component/slice/slice.component.tsx
- FE/src/app/modules/client/home/main-home/main-home.component.tsx
- FE/src/app/modules/client/home/sidebar-home/sidebar-home.component.tsx
tôi đã reponesive xong phần ui home-page
refs:DTNF-23
> style:reponsive ui home-page of the client

- BE/middlewares/authorization.js
- BE/routers/product.js
t bug xong phần middlewares
refs:DTNF-27
> bug:DTNF-27-be-create-middlewares

- BE/modules/Cart/Model/Cart.js
Tôi đã sửa xong model carts
refs:DTNF-30
> bug:create-model-api-carts

- BE/modules/Cart/Controller/Api/addCart.js
- BE/modules/Cart/Controller/index.js
- BE/modules/Cart/Service/Cart.js
- BE/routers/cart.js
t đã làm xong phần addCart
refs: DTNF-34
> feact: DTNF-34-be-create-api-add-carts

- FE/src/app/component/parts/input/input.component.tsx
- FE/src/app/component/parts/itemproduct/itemproduct.component.tsx
- FE/src/app/container/default-home/default-home.component.tsx
- FE/src/app/modules/client/home/home.component.tsx
- FE/src/app/modules/client/home/main-home/component/list-product/list-product.component.tsx
- FE/src/app/modules/client/home/sidebar-home/sidebar-home.component.tsx
tôi đã chỉnh lại 1 số lỗi reponesive của trang homepage refs:DTNF-23
> bug:reponsive-ui-home-page-of-the-client

- BE/modules/Cart/Model/Cart.js
- BE/modules/Color/Controller/Api/addColor.js
tôi đã fix bug xog model api cart và chỉnh lại nghiệp vụ api add color
> bug:fixbug model api cart and api add color

- BE/modules/Cart/Model/Cart.js
- BE/modules/Color/Controller/Api/deleteColor.js
- BE/modules/Color/Controller/Api/getAllColor.js
- BE/modules/Color/Controller/Api/getOneColor.js
- BE/modules/Color/Controller/Api/updateColor.js
- BE/modules/Color/Controller/index.js
- BE/modules/Color/Service/Color.js
- BE/modules/Product/Model/Product.js
- BE/routers/color.js
Tôi đã làm xong api crud color và update model cart, model product refs:DTNF-39
> feat:create-api-crud-color

- BE/modules/Auth/service/Auth.js
- BE/modules/Cart/Service/Cart.js
tôi đã fix xong phần getAllCarts và update phần login 
refs:DTNF-31
> bug:DTNF-31-be-create-api-getall-carts

- BE/modules/Cart/Controller/Api/deleteCart.js
- BE/modules/Cart/Service/Cart.js
- BE/routers/cart.js
Sửa phần Create api delete-carts
ref: DTNF-32
> Bug:be-create-api-delete-carts

- BE/modules/Cart/Controller/Api/addCart.js
- BE/modules/Cart/Model/Cart.js
- BE/modules/Cart/Service/Cart.js
- BE/modules/Product/Controller/Api/addProduct.js
- BE/modules/Product/Model/Product.js
- BE/modules/Product/Service/Product.js
- BE/routers/product.js
tôi đã chỉnh xong lỗi api add cart và update lại api add product
> bug:fix api add cart and update api add product

- FE/src/app/component/stack/footer/footer.component.tsx
Tôi đã fix bug responsive footer
> bug: responsive_component_ footer

- BE/modules/Cart/Controller/Api/addCart.js
- BE/modules/Cart/Model/Cart.js
- BE/modules/Cart/Service/Cart.js
- BE/routers/product.js
- FE/src/app/container/default-home/default-home.component.tsx
tôi đã fix bug xog api add to cart
> bug: bug api add to cart

- BE/modules/Cart/Controller/Api/addCart.js
- BE/modules/Order/Model/Order.js
- BE/modules/Order/controller/api/addOrder.js
- BE/modules/Order/controller/index.js
- BE/modules/Order/service/orderService.js
- BE/routers/order.js
- BE/routers/router.js
tôi đã làm xong api add order và fix lỗi model order refs:DTNF-36
> feat:be-create-api-add-order

- BE/modules/Cart/Controller/Api/updateCart.js
- BE/modules/Cart/Service/Cart.js
- BE/routers/cart.js
> bug:be-create-api-update-carts

- BE/modules/Order/controller/api/updateOrder.js
- BE/modules/Order/controller/index.js
- BE/modules/Order/service/orderService.js
- BE/routers/order.js
đã làm xong api update order
refs:DTNF-37
> feat:be-create-api-update-order

- BE/middlewares/authorization.js
- BE/modules/Cart/Controller/Api/addCart.js
- BE/modules/Category/Controller/Api/getAllCategory.js
- BE/modules/Category/Service/Category.js
- BE/modules/Color/Controller/Api/getAllColor.js
- BE/modules/Color/Service/Color.js
- BE/modules/Product/Controller/Api/addProduct.js
- BE/modules/Product/Controller/Api/getAllProduct.js
- BE/modules/Product/Model/Product.js
- BE/modules/Product/Service/Product.js
- BE/package.json
- BE/routers/cart.js
- BE/routers/category.js
- BE/routers/color.js
- BE/routers/product.js
tôi đã fix xong phần check quyền của tất cả api
> bug: fixbug check permissions all api

- BE/modules/size/Controller/Api/addSize.js
- BE/modules/size/Controller/Api/deleteSize.js
- BE/modules/size/Controller/Api/getAllSize.js
- BE/modules/size/Controller/Api/getOneSize.js
- BE/modules/size/Controller/Api/updateSize.js
- BE/modules/size/Controller/index.js
- BE/modules/size/Model/size.js
- BE/modules/size/Service/size.js
- BE/routers/router.js
- BE/routers/size.js
> bug;[BE]-CRUD-Api-size

- FE/src/app/modules/client/instruct-seller/instruct-seller.component.tsx
- FE/src/app/modules/client/router.tsx
Tôi đã làm xong ui instruct seller
refs:DTNF-42
> style:create-ui-instruct-seller

- BE/modules/Capacity/Controller/Api/addCapacity.js
- BE/modules/Capacity/Controller/Api/deleteCapacity.js
- BE/modules/Capacity/Controller/Api/getAllCapacity.js
- BE/modules/Capacity/Controller/Api/getOneCapacity.js
- BE/modules/Capacity/Controller/Api/updateCapacity.js
- BE/modules/Capacity/Controller/index.js
- BE/modules/Capacity/Model/capacity.js
- BE/modules/Capacity/Service/Capacity.js
- BE/modules/size/Controller/Api/getAllSize.js
- BE/routers/capacity.js
- BE/routers/router.js
Tôi đã làm xong create-crud-and-model-api-capacity refs:DTNF-45
> feat:create-crud-and-model-api-capacity

- FE/src/App.tsx
- FE/src/app/component/stack/footer/paymentFooter.componet.tsx
- FE/src/app/component/stack/header/payment-header.component.tsx
- FE/src/app/container/default-checkout/default-checkout.component.tsx
- FE/src/app/modules/client/checkout/payment/main-payment/component/banks/payments.componet.tsx
- FE/src/app/modules/client/checkout/payment/main-payment/component/deliver/deliver.component.tsx
- FE/src/app/modules/client/checkout/payment/main-payment/main-payment.component.tsx
- FE/src/app/modules/client/checkout/payment/payment.component.tsx
- FE/src/app/modules/client/checkout/payment/side-payment/side-payment.component.tsx
- FE/src/app/modules/client/router.tsx
tôi đã làm xong phần ui-paymant-of-the-client
refs: DTNF-41
> style:create-ui-paymant-of-the-client

- FE/src/app/component/stack/header/header.component.tsx
- FE/src/app/modules/client/cart/cart.component.tsx
- FE/src/app/modules/client/cart/cart.type.tsx
- FE/src/app/modules/client/cart/components/leftCart/leftCart.component.tsx
- FE/src/app/modules/client/cart/components/rightCart/rightinner.component.tsx
- FE/src/app/modules/client/router.tsx
hoàn thành phần ui-cart-of-client
refs:DTNF-40
> style:fe-create-ui-cart-of-the-client

- FE/package-lock.json
- FE/package.json
- FE/src/App.tsx
- FE/src/app/component/parts/input/input.component.tsx
- FE/src/app/component/stack/footer/paymentFooter.componet.tsx
- FE/src/app/component/stack/header/headerCheckout.tsx
- FE/src/app/modules/client/checkout/checkout.component.tsx
- FE/src/app/modules/client/checkout/shipping/shipping.component.tsx
- FE/src/app/modules/client/utils/validateForm.ts
t đã làm xong phần UI shipping
refs:DTNF-43
> style: fe-create-ui-shipping-of-the-client

- FE/src/app/modules/client/instruct-seller/instruct-seller.component.tsx
Tôi đã làm xong reponsive ui instruct seller
refs:DTNF-46
> style:create-reponsive-ui-instruct-seller

- FE/src/app/component/parts/buttonSqua/ButtonSqua.tsx
- FE/src/app/component/parts/quantity/QuantityProduct.tsx
- FE/src/app/modules/client/detail/main-detail/components/detail-information/detail.infomation.component.tsx
Chỉnh lại phần create ui product detail
ref: DTNF-16
> bug: fe-create-componet-ui-product-detail-of-the-client

- FE/src/app/component/stack/footer/paymentFooter.componet.tsx
- FE/src/app/component/stack/header/payment-header.component.tsx
- FE/src/app/modules/client/checkout/payment/main-payment/component/banks/payments.componet.tsx
- FE/src/app/modules/client/checkout/payment/main-payment/component/deliver/deliver.component.tsx
- FE/src/app/modules/client/checkout/payment/main-payment/main-payment.component.tsx
- FE/src/app/modules/client/checkout/payment/payment.component.tsx
- FE/src/app/modules/client/checkout/payment/side-payment/side-payment.component.tsx
> Tôi đã làm xong reponsive-component-ui-payment-of-the-client

- FE/src/app/component/stack/header/headerCheckout.tsx
- FE/src/app/modules/client/checkout/checkout.component.tsx
- FE/src/app/modules/client/checkout/shipping/shipping.component.tsx
t đã reponsive xong phần ui-shipping-of-the-client refs:DTNF-49
> style:DTNF-49-fe-reponsive-component-ui-shipping-of-the-client

- FE/src/app/modules/client/cart/cart.component.tsx
- FE/src/app/modules/client/cart/components/leftCart/leftCart.component.tsx
- FE/src/app/modules/client/cart/components/rightCart/rightinner.component.tsx
- FE/src/app/modules/client/home/home.component.tsx
- FE/src/index.css
Hoàn thành reponsive component-ui-cart
refs:DTNF-51
> style:fe-reponsive-compoent-ui-cart-of-the-client

- FE/src/app/component/stack/header/header.component.tsx
- FE/src/app/modules/client/accountLogin/accountLogin.component.tsx
- FE/src/app/modules/client/accountLogin/form/signIn.component.tsx
- FE/src/app/modules/client/accountLogin/form/signUp.component.tsx
Tôi đã làm xong ui login vs register
refs:  DTNF-47
> style: fe-create-ui-login-and-register

- FE/src/app/component/parts/quantity/QuantityProduct.tsx
- FE/src/app/modules/client/cart/components/leftCart/leftCart.component.tsx
- FE/src/app/modules/client/checkout/shipping/shipping.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/detail-information/detail.infomation.component.tsx
Sửa xong button quantity ở trang cart và reponsive refs:DTNF-51
> bug:fe-reponsive-compoent-ui-cart-of-the-client

- FE/src/app/component/parts/itemproduct/itemproduct.component.tsx
- FE/src/app/modules/client/detail/detail.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/detail-information/detail.infomation.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/list-product/list-product.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/preview-img/preview.img.component.tsx
- FE/src/app/modules/client/home/main-home/component/list-product/list-product.component.tsx
- FE/src/app/modules/client/redux/hook/useProductReducer.ts
- FE/src/app/modules/client/redux/reducer/productSlice/productSlice.ts
- FE/src/app/modules/client/redux/reducer/productSlice/thunk/product.thunk.ts
- FE/src/app/modules/client/router.tsx
đã làm xong detailed-product-display
refs:DTNF-54
> feat:fe-detailed-product-display

- FE/src/app/modules/client/detail/main-detail/components/detail-information/detail.infomation.component.tsx
- FE/src/app/modules/client/helper/tranform.data.ts
đã làm xong do-logic-function-when-selecting-product-parameters refs: DTNF-56
> feat:do-logic-function-when-selecting-product-parameters

- BE/modules/Cart/Controller/Api/getAllCart.js
- BE/modules/Cart/Service/Cart.js
- FE/src/app/api/configHttp.ts
- FE/src/app/component/parts/quantity/QuantityProduct.tsx
- FE/src/app/component/stack/header/header.component.tsx
- FE/src/app/modules/client/cart/components/leftCart/leftCart.component.tsx
- FE/src/app/modules/client/redux/hook/useCartReducer.ts
- FE/src/app/modules/client/redux/reducer/cartSlice/cartSlice.ts
- FE/src/app/modules/client/redux/reducer/cartSlice/thunk/cart.thunk.ts
- FE/src/app/modules/client/redux/reducer/index.ts
đã làm xog show-products-to-cart và fix lỗi nhỏ api getall cart refs:DTNF-59
> feat: DTNF-59-fe-show-products-to-cart

- FE/src/app/api/cart/cart.api.ts
- FE/src/app/api/configHttp.ts
- FE/src/app/component/parts/button/ButtonSqua.tsx
- FE/src/app/component/parts/quantity/QuantityProduct.tsx
- FE/src/app/component/stack/header/header.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/detail-information/detail.infomation.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/preview-img/preview.img.component.tsx
- FE/src/app/modules/client/redux/reducer/cartSlice/cartSlice.ts
- FE/src/app/modules/client/redux/reducer/productSlice/productSlice.ts
đã làm xong add-product-to-cart
refs: DTNF-57
> feat:fe-add-product-to-cart

- BE/modules/Cart/Controller/Api/addCart.js
- FE/src/app/api/configHttp.ts
đã fix xog api add product to cart
> bug: fixbug api add product to cart

- BE/modules/Product/Controller/Api/addProduct.js
- FE/src/app/api/configHttp.ts
- FE/src/app/component/parts/quantity/quantitySelect.tsx
- FE/src/app/modules/client/cart/components/leftCart/leftCart.component.tsx
- FE/src/app/modules/client/redux/reducer/cartSlice/cartSlice.ts
đã làm xog implement-the-function-to-change-the-parameters-in-the-cart
> feat:the-function-to-change-parameters-in-the-cart

- FE/src/app/modules/client/home/sidebar-home/sidebar-home.component.tsx
- FE/src/app/modules/client/redux/hook/useCategoryReducer.ts
- FE/src/app/modules/client/redux/reducer/categorySlice/categorySlice.ts
- FE/src/app/modules/client/redux/reducer/categorySlice/thunk/category.thunk.ts
- FE/src/app/modules/client/redux/reducer/index.ts
đã làm xong show-all-categories
refs:DTNF-62
> feat:fe-show-all-categories

- FE/src/app/modules/client/accountLogin/accountLogin.component.tsx
- FE/src/app/modules/client/accountLogin/form/signIn.component.tsx
- FE/src/app/modules/client/accountLogin/form/signUp.component.tsx
Tôi đã fix xong lỗi UI
refs: DNTF-47
> bug: UI login vs register

- FE/src/app/api/configHttp.ts
- FE/src/app/component/parts/input/input.component.tsx
- FE/src/app/component/parts/quantity/quantitySelect.tsx
- FE/src/app/modules/client/cart/components/leftCart/leftCart.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/decription/description.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/detail-information/detail.infomation.component.tsx
- FE/src/app/modules/client/home/main-home/component/list-product/list-product.component.tsx
tôi đã fix xong bug value input and  logic
> bug:fixbug value input and  logic

- FE/src/app/api/configHttp.ts
- FE/src/app/component/stack/header/headerCheckout.tsx
- FE/src/app/component/stack/header/payment-header.component.tsx
- FE/src/app/modules/client/cart/components/leftCart/leftCart.component.tsx
- FE/src/app/modules/client/cart/components/rightCart/rightinner.component.tsx
- FE/src/app/modules/client/checkout/payment/main-payment/component/deliver/deliver.component.tsx
- FE/src/app/modules/client/checkout/payment/main-payment/main-payment.component.tsx
- FE/src/app/modules/client/checkout/payment/side-payment/side-payment.component.tsx
- FE/src/app/modules/client/home/sidebar-home/sidebar-home.component.tsx
đã làm xong display-data-on-the-payment-page
refs:DTNF-63
> feat:display-data-on-the-payment-page

- BE/modules/Auth/service/Auth.js
- BE/modules/Cart/Controller/Api/updateCart.js
- BE/modules/Cart/Service/Cart.js
- FE/src/App.tsx
- FE/src/app/api/cart/cart.api.ts
- FE/src/app/api/configHttp.ts
- FE/src/app/component/parts/quantity/quantitySelect.tsx
- FE/src/app/modules/client/cart/components/leftCart/leftCart.component.tsx
- FE/src/app/modules/client/redux/reducer/cartSlice/cartSlice.ts
đã fix xong bug  update cart and save database
> feat:fixbug update cart and save database

- BE/modules/Cart/Controller/Api/deleteCart.js
- BE/modules/Cart/Service/Cart.js
- BE/routers/cart.js
- FE/src/app/api/cart/cart.api.ts
- FE/src/app/modules/client/cart/components/leftCart/leftCart.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/detail-information/detail.infomation.component.tsx
- FE/src/app/modules/client/redux/reducer/cartSlice/cartSlice.ts
đã làm xong delete products in cart
refs:DTNF-64
> feat:fe-delete-products-in-cart

- FE/src/app/component/stack/footer/paymentFooter.componet.tsx
> bug: fix bug react format error

- FE/src/app/component/parts/quantity/quantitySelect.tsx
- FE/src/app/modules/client/cart/components/leftCart/leftCart.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/detail-information/detail.infomation.component.tsx
- FE/src/app/modules/client/helper/tranform.data.ts
đã fix xong bug ui cart ant react format error
> bug:fix bug ui cart ant react format error

- FE/src/app/api/configHttp.ts
- FE/src/app/component/stack/header/header.component.tsx
- FE/src/app/modules/client/accountLogin/form/forgotPassword.component.tsx
- FE/src/app/modules/client/accountLogin/form/signInAndRegister.component.tsx
- FE/src/app/modules/client/accountLogin/form/signInWithEmail.component.tsx
- FE/src/app/modules/client/accountLogin/requireAuth.component.tsx
- FE/src/app/modules/client/cart/cart.component.tsx
- FE/src/app/modules/client/redux/hook/useAuthReducer.ts
- FE/src/app/modules/client/redux/reducer/authSlice/authSlice.ts
- FE/src/app/modules/client/redux/reducer/index.ts
- FE/src/app/modules/client/router.tsx
đã làm xong checkwhen customer no logged perform function refs:DTNF-66
> feat:checkwhen customer no logged perform function

- FE/src/app/api/auth/auth.api.ts
- FE/src/app/api/configHttp.ts
- FE/src/app/component/parts/input/input.component.tsx
- FE/src/app/component/parts/quantity/quantitySelect.tsx
- FE/src/app/component/stack/header/header.component.tsx
- FE/src/app/container/default-home/default-home.component.tsx
- FE/src/app/modules/client/accountLogin/form/signInWithEmail.component.tsx
- FE/src/app/modules/client/accountLogin/requireAuth.component.tsx
- FE/src/app/modules/client/cart/cart.component.tsx
- FE/src/app/modules/client/redux/reducer/authSlice/authSlice.ts
- FE/src/app/modules/client/redux/reducer/cartSlice/cartSlice.ts
- FE/src/app/modules/client/router.tsx
- FE/src/app/modules/client/utils/validateForm.ts
đã làm xong create function login
refs:DTNF-68
> feat:fe-create-function-login

- FE/src/app/component/parts/quantity/quantitySelect.tsx
- FE/src/app/component/stack/swiper-list/swiper-list.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/detail-information/detail.infomation.component.tsx
- FE/src/app/modules/client/redux/reducer/cartSlice/cartSlice.ts
đã  fixbug select quantity cart
> bug: bug/ fixbug-select-quantity-cart

- FE/src/app/component/parts/input/input.component.tsx
- FE/src/app/component/stack/header/header.component.tsx
- FE/src/app/modules/client/router.tsx
- FE/src/app/modules/client/search/component/address-search/address-search.component.tsx
- FE/src/app/modules/client/search/component/filter-product/filter.component.tsx
- FE/src/app/modules/client/search/component/list-product/list-product.component.tsx
- FE/src/app/modules/client/search/search.component.tsx
Tôi đã làm xong product search funtion
refs:DTNF-60
> feat:create-product-search-function

- FE/src/app/component/stack/header/header.component.tsx
đã làm xong create-function-logout
refs: DTNF-69
> feat: create-function-logout

- FE/src/app/component/parts/button/ButtonSqua.tsx
- FE/src/app/component/stack/footer/footer.component.tsx
> bug: UI Footer

- FE/src/app/modules/client/cart/cart.component.tsx
- FE/src/app/modules/client/cart/components/leftCart/leftCart.component.tsx
- FE/src/app/modules/client/cart/components/rightCart/rightinner.component.tsx
- FE/src/app/modules/client/home/main-home/component/slice/slice.component.tsx
> bug:update ui cart

- FE/src/app/component/stack/header/header.component.tsx
- FE/src/app/component/stack/menu-sidebar/menu-sidebar.component.tsx
- FE/src/app/modules/client/cart/components/rightCart/rightinner.component.tsx
- FE/src/app/modules/client/manage-order/component/main-manage-order/main-manage-order.component.tsx
- FE/src/app/modules/client/manage-order/manage-order.component.tsx
- FE/src/app/modules/client/router.tsx
tôi đã làm xong ui manage order
refs:DTNF-72
> style:fe create ui manage order

- FE/src/app/component/stack/footer/footer.component.tsx
- FE/src/app/component/stack/header/header.component.tsx
- FE/src/app/modules/client/home/home.component.tsx
- FE/src/app/modules/client/products/listProduct/listProducts.component.tsx
- FE/src/app/modules/client/products/products.component.tsx
- FE/src/app/modules/client/products/sidebarProducts/sidebarProducts.component.tsx
- FE/src/app/modules/client/products/titleProducts/titleProducts.component.tsx
- FE/src/app/modules/client/router.tsx
Tôi đã làm xong UI listProducts
refs: DTNF-71
> style:fe-create-ui-list-product

- BE/modules/Order/Model/Order.js
- BE/modules/Order/service/orderService.js
- BE/routers/order.js
- FE/src/app/api/order/order.api.ts
- FE/src/app/modules/client/checkout/checkout.component.tsx
- FE/src/app/modules/client/checkout/component/shipping/shipping.component.tsx
- FE/src/app/modules/client/checkout/component/side-payment/side-payment.component.tsx
Hoàn thành phần order-product
ref:DTNF-65
> feat:DTNF-65-fe-order-product

- BE/modules/Order/service/orderService.js
- FE/package-lock.json
- FE/package.json
- FE/src/app/component/parts/spinner/spinner.component.tsx
- FE/src/app/component/stack/layout-loadding/layout-loadding.component.tsx
- FE/src/app/modules/client/checkout/checkout.component.tsx
- FE/src/main.tsx
đã làm xong loadding order
refs:DTNF-73
> style: fe create loadding order

- FE/src/app/component/stack/header/header.component.tsx
- FE/src/app/modules/client/aboutUs/communityActivities.component.tsx
- FE/src/app/modules/client/aboutUs/fashionShow.component.tsx
- FE/src/app/modules/client/aboutUs/generalIntroduction.component.tsx
- FE/src/app/modules/client/products/listProduct/listProducts.component.tsx
- FE/src/app/modules/client/products/products.component.tsx
- FE/src/app/modules/client/products/sidebarProducts/sidebarProducts.component.tsx
- FE/src/app/modules/client/products/titleProducts/titleProducts.component.tsx
- FE/src/app/modules/client/router.tsx
Tôi đã làm xong UI about-us
refs: DTNF-75
> style:-fe-create-ui-about-us

- FE/src/app/api/auth/auth.api.ts
- FE/src/app/component/parts/quantity/QuantityProduct.tsx
- FE/src/app/modules/client/accountLogin/register.component.tsx
- FE/src/app/modules/client/cart/components/leftCart/leftCart.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/detail-information/detail.infomation.component.tsx
- package-lock.json
Đã làm xong function register, update 1 số UI
refs: DTNF-67
> feat: fe-create-function-register

- BE/modules/Product/Service/Product.js
- FE/src/app/component/parts/itemproduct/itemproduct.component.tsx
- FE/src/app/contants/contants.client.ts
- FE/src/app/modules/client/cart/cart.component.tsx
- FE/src/app/modules/client/cart/components/rightCart/rightinner.component.tsx
- FE/src/app/modules/client/checkout/checkout.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/detail-information/detail.infomation.component.tsx
- FE/src/app/modules/client/home/main-home/component/new-product/new-product.component.tsx
- FE/src/app/modules/client/home/main-home/component/sale-product/sale-product.component.tsx
- FE/src/app/modules/client/products/listProduct/listProducts.component.tsx
- FE/src/app/modules/client/redux/reducer/authSlice/authSlice.ts
đã làm fix xong ui and  logic project
> bug:update ui and  logic project

- FE/src/App.tsx
- FE/src/app/api/cart/cart.api.ts
- FE/src/app/component/stack/header/header.component.tsx
- FE/src/app/container/defaul-admin/defaul-admin.component.tsx
- FE/src/app/modules/admin/constance/menu-dashboard.tsx
- FE/src/app/modules/admin/order/order.component.tsx
- FE/src/app/modules/admin/product/product.component.tsx
- FE/src/app/modules/admin/router.tsx
- FE/src/app/modules/admin/user/user.component.tsx
- FE/src/app/modules/client/accountLogin/login.component.tsx
- FE/src/app/modules/client/cart/cart.component.tsx
- FE/src/app/modules/client/cart/components/leftCart/leftCart.component.tsx
- FE/src/app/modules/client/cart/components/rightCart/rightinner.component.tsx
- FE/src/app/modules/client/checkout/checkout.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/detail-information/detail.infomation.component.tsx
- FE/src/app/modules/client/manage-order/manage-order.component.tsx
- FE/src/app/modules/client/redux/reducer/authSlice/authSlice.ts
đã làm xong :create management framework admin và 1 số bug cũ refs:DTNF-77
> style:create management framework admin

- BE/modules/Auth/Controller/Api/getAllUser.js
- BE/modules/Auth/Controller/index.js
- BE/modules/Auth/service/Auth.js
- BE/routers/auth.js
- FE/src/app/component/parts/spinner/spinner.component.tsx
- FE/src/app/component/stack/layout-loadding/layout-loadding.component.tsx
- FE/src/app/modules/admin/common/template-modal/template-modal.component.tsx
- FE/src/app/modules/admin/common/template-table/template-table.component.tsx
- FE/src/app/modules/admin/user/service/user.service.ts
- FE/src/app/modules/admin/user/user.component.tsx
- FE/src/app/modules/client/manage-order/component/main-manage-order/main-manage-order.component.tsx
- FE/src/index.css
Đã hoàn thành ui admin user and logic getall user
refs:DTNF-81
> feat:create ui admin user and logic getall user

- FE/src/app/modules/client/checkout/checkout.component.tsx
- FE/src/app/modules/client/router.tsx
- FE/src/app/modules/client/thank-Customers/thankCustomers.component.tsx
chỉnh lại ui thank-customers
refs: DTNF-76
> style: fe-create-ui-thank-customers

- FE/src/app/modules/admin/category/category.component.tsx
- FE/src/app/modules/admin/category/service/category.service.tsx
- FE/src/app/modules/admin/constance/menu-dashboard.tsx
- FE/src/app/modules/admin/router.tsx
Đã hoàn thành ui admin category and logic getall category refs:DTNF-83
> feat:create-ui-admin-category-and-logic-getall-category

- FE/src/app/modules/admin/common/template-modal/template-modal.component.tsx
- FE/src/app/modules/admin/common/template-table/template-table.component.tsx
- FE/src/app/modules/admin/user/user.component.tsx
đã fix xong  logic template admin
> bug:update logic template admin

- FE/src/app/modules/admin/product/product.component.tsx
- FE/src/app/modules/admin/product/service/product.service.ts
đã làm xong  ui admin product and logic getall product refs: DTNF-82
> feat:create ui admin product and logic getall product

- FE/src/app/modules/admin/category/category.component.tsx
- FE/src/app/modules/admin/product/product.component.tsx
đã fix xong bug logic getall product and category
> bug:fix bug logic getall product and category

- BE/modules/Auth/Controller/Api/getOneUser.js
- BE/modules/Auth/Controller/index.js
- BE/modules/Auth/service/Auth.js
- BE/routers/auth.js
- FE/src/app/component/parts/button/ButtonSqua.tsx
- FE/src/app/component/stack/header/header.component.tsx
- FE/src/app/component/stack/menu-sidebar/menu-sidebar.component.tsx
- FE/src/app/modules/client/accountLogin/login.component.tsx
- FE/src/app/modules/client/accountLogin/register.component.tsx
- FE/src/app/modules/client/manager-info-customer/component/updatePassword.component.tsx
- FE/src/app/modules/client/manager-info-customer/manage-info-customer.component.tsx
- FE/src/app/modules/client/redux/hook/useAuthReducer.ts
- FE/src/app/modules/client/redux/reducer/authSlice/authSlice.ts
- FE/src/app/modules/client/redux/reducer/authSlice/thunk/auth.thunk.ts
- FE/src/app/modules/client/router.tsx
- FE/src/app/modules/client/support/support.component.tsx
- FE/src/app/modules/client/utils/validateForm.ts
Tôi đã làm xong ui account information và ui support 
ref:DTNF-86
> style:create-ui-account-information-and-support

- BE/config/configImage.js
- BE/modules/Auth/Controller/Api/deleteUser.js
- BE/modules/Auth/Controller/index.js
- BE/modules/Auth/service/Auth.js
- BE/modules/Category/Controller/Api/deleteCategory.js
- BE/routers/auth.js
- FE/src/app/container/defaul-admin/defaul-admin.component.tsx
- FE/src/app/modules/admin/category/category.component.tsx
- FE/src/app/modules/admin/common/template-table/template-table.component.tsx
- FE/src/app/modules/admin/constance/menu-dashboard.tsx
- FE/src/app/modules/admin/product/product.component.tsx
- FE/src/app/modules/admin/user/service/user.service.ts
- FE/src/app/modules/admin/user/user.component.tsx
đã làm xong function adduser and deleteuser admin
refs:DTNF-87
> feat:function adduser and deleteuser admin

- BE/modules/Auth/Controller/Api/updateUser.js
- BE/modules/Auth/Controller/index.js
- BE/modules/Auth/Model/Auth.js
- BE/modules/Auth/service/Auth.js
- BE/modules/Product/Controller/Api/addProduct.js
- BE/routers/auth.js
- BE/routers/category.js
- FE/src/app/api/auth/auth.api.ts
- FE/src/app/modules/admin/category/category.component.tsx
- FE/src/app/modules/admin/category/service/category.service.tsx
- FE/src/app/modules/admin/user/service/user.service.ts
- FE/src/app/modules/admin/user/user.component.tsx
đã làm xong  update user and delete category admin refs:DTNF-88
> feat:funtion update user and delete category admin

- FE/src/app/modules/client/products/products.component.tsx
- FE/src/app/modules/client/products/sidebarProducts/sidebarProducts.component.tsx
- FE/src/app/modules/client/router.tsx
refs: DTNF-80
Tôi đã làm xong search-products-by-price và xóa search router
> feat:fe-create-function-search-products-by-price

- BE/modules/Order/controller/api/deleteOrder.js
- BE/modules/Order/controller/index.js
- BE/modules/Order/service/orderService.js
- BE/routers/order.js
- FE/src/app/api/order/order.api.ts
- FE/src/app/modules/admin/order/order.component.tsx
- FE/src/app/modules/admin/order/service/order.service.tsx
- FE/src/app/modules/client/cart/components/leftCart/leftCart.component.tsx
- FE/src/app/modules/client/checkout/checkout.component.tsx
- FE/src/app/modules/client/manage-order/component/main-manage-order/main-manage-order.component.tsx
- FE/src/app/modules/client/redux/reducer/cartSlice/cartSlice.ts
- FE/src/app/modules/client/router.tsx
- package-lock.json
đã làm xong function cancel order
refs:DTNF-89
> feat:create-function-cancel-order

- FE/src/app/component/parts/spinner/spinner.component.tsx
- FE/src/app/component/stack/menu-sidebar/menu-sidebar.component.tsx
- FE/src/app/modules/client/checkout/checkout.component.tsx
- FE/src/app/modules/client/manager-info-customer/manage-info-customer.component.tsx
Tôi đã fix xong bug value input order và input manager customer
> bug:fix bug value input order and value input manager info customer

- BE/modules/Auth/Controller/Api/deleteUser.js
- BE/modules/Cart/Controller/Api/addCart.js
- BE/modules/Cart/Service/Cart.js
- BE/modules/Category/Model/Category.js
- BE/modules/Category/Service/Category.js
- BE/routers/category.js
- FE/src/app/component/parts/quantity/quantitySelect.tsx
- FE/src/app/component/stack/header/header.component.tsx
- FE/src/app/component/stack/menu-sidebar/menu-sidebar.component.tsx
- FE/src/app/modules/admin/category/category.component.tsx
- FE/src/app/modules/admin/category/service/category.service.tsx
- FE/src/app/modules/admin/common/template-table/template-table.component.tsx
- FE/src/app/modules/admin/constance/menu-dashboard.tsx
- FE/src/app/modules/admin/product/product.component.tsx
- FE/src/app/modules/admin/router.tsx
- FE/src/app/modules/admin/user/user.component.tsx
- FE/src/app/modules/admin/vocher/vorcher.component.tsx
- FE/src/app/modules/client/cart/cart.component.tsx
- FE/src/app/modules/client/cart/components/leftCart/leftCart.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/detail-information/detail.infomation.component.tsx
- FE/src/app/modules/client/manage-order/component/main-manage-order/main-manage-order.component.tsx
- FE/src/app/modules/client/manage-order/manage-order.component.tsx
- FE/src/app/modules/client/redux/reducer/cartSlice/cartSlice.ts
đã làm xong crud category admin vs fix logic delete user refs:DTNF-93
> feat: crud category admin vs fix logic delete user

- BE/modules/Order/controller/api/deleteOrder.js
- FE/index.html
- FE/package-lock.json
- FE/package.json
- FE/src/app/api/address/address.api.ts
- FE/src/app/modules/client/checkout/checkout.component.tsx
- FE/src/app/modules/client/checkout/component/shipping/shipping.component.tsx
- FE/tsconfig.json
đã làm xong integrate api provinces cities and districts
refs: DTNF-96
> feat: integrate api provinces cities and districts

- FE/src/app/modules/client/products/products.component.tsx
- FE/src/app/modules/client/products/sidebarProducts/sidebarProducts.component.tsx
refs: DTNF-91
đã làm xong sort-prices-from-low-to-high-from-high-to-low
> feat:fe-sort-prices-from-low-to-high-from-high-to-low

- FE/src/app/modules/admin/category/category.component.tsx
- FE/src/app/modules/admin/common/template-table/template-table.component.tsx
- FE/src/app/modules/admin/order/order.component.tsx
- FE/src/app/modules/admin/product/product.component.tsx
- FE/src/app/modules/admin/user/user.component.tsx
- FE/src/app/modules/admin/vocher/vorcher.component.tsx
- FE/src/app/modules/client/cart/components/leftCart/leftCart.component.tsx
- FE/src/app/modules/client/checkout/checkout.component.tsx
- FE/src/app/modules/client/checkout/component/side-payment/side-payment.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/detail-information/detail.infomation.component.tsx
- FE/src/app/modules/client/manage-order/component/main-manage-order/main-manage-order.component.tsx
- FE/src/app/modules/client/redux/hook/useVorcherReducer.ts
- FE/src/app/modules/client/redux/reducer/cartSlice/cartSlice.ts
- FE/src/app/modules/client/redux/reducer/index.ts
- FE/src/app/modules/client/redux/reducer/vorcher/thunk/vorcher.thunk.ts
- FE/src/app/modules/client/redux/reducer/vorcher/vorcher.Slice.ts
đã làm xong vorcher api integration applie order 1million refs:DTNF-97
> feat:vorcher api integration applie order 1million

- FE/src/app/component/stack/menu-sidebar/menu-sidebar.component.tsx
- FE/src/app/container/defaul-admin/defaul-admin.component.tsx
- FE/src/app/modules/admin/common/template-table/template-table.component.tsx
- FE/src/app/modules/admin/order/order.component.tsx
- FE/src/app/modules/admin/product/product.component.tsx
- FE/src/app/modules/client/detail/main-detail/main-detail.component.tsx
- FE/src/app/modules/client/home/main-home/component/gallery/gallery.component.tsx
- FE/src/app/modules/client/home/main-home/component/new-product/new-product.component.tsx
- FE/src/app/modules/client/home/main-home/component/sale-product/sale-product.component.tsx
- FE/src/app/modules/client/products/sidebarProducts/sidebarProducts.component.tsx
refs:DTNF-98
Tôi đã làm xong update-ui-admin
> style:fe-update-ui-admin

- BE/.env
- BE/config/configVnpay.js
- BE/modules/payment/controller/createUrlPayment.controller.js
- BE/modules/payment/controller/getStatusPayment.controller.js
- BE/modules/payment/service/payment.service.js
- BE/package-lock.json
- BE/package.json
- BE/routers/payment.js
- BE/routers/router.js
- BE/server.js
- FE/src/app/api/payment/payment.api.ts
- FE/src/app/component/parts/quantity/quantitySelect.tsx
- FE/src/app/modules/admin/constance/menu-dashboard.tsx
- FE/src/app/modules/admin/payment/payment.component.tsx
- FE/src/app/modules/admin/router.tsx
- FE/src/app/modules/client/cart/components/leftCart/leftCart.component.tsx
- FE/src/app/modules/client/checkout/checkout.component.tsx
- FE/src/app/modules/client/checkout/component/payments/payments.componet.tsx
- FE/src/app/modules/client/checkout/component/side-payment/side-payment.component.tsx
- FE/src/app/modules/client/redux/reducer/cartSlice/cartSlice.ts
- FE/src/app/modules/client/redux/reducer/orderSlice/orderSlice.ts
đã làm xong :create online payment function using vnpay refs:DTNF-78
> feat:create online payment function using vnpay

- FE/package-lock.json
- FE/package.json
- FE/src/app/modules/admin/constance/menu-dashboard.tsx
- FE/src/app/modules/admin/router.tsx
- FE/src/app/modules/admin/statistics/service/statistics.service.ts
- FE/src/app/modules/admin/statistics/statistics.component.tsx
đã làm xong create statistics by day
refs:DTNF-102
> feat:create statistics by day

- FE/src/app/modules/admin/statistics/statistics.component.tsx
đã làm xong create weekly statistics
refs:DTNF-103
> feat: create weekly statistics

- FE/src/app/modules/admin/statistics/statistics.component.tsx
đã làm xong statistics by month and by year
refs:DTNF-104
> feat: create statistics by month and by year

- FE/src/app/modules/client/products/listProduct/listProducts.component.tsx
- FE/src/app/modules/client/products/products.component.tsx
- FE/src/app/modules/client/products/sidebarProducts/sidebarProducts.component.tsx
> feact: fe latest product arrangement

- BE/.env
- BE/modules/Auth/Controller/Api/forgotPassword.js
- BE/modules/Auth/Controller/index.js
- BE/modules/Auth/service/Auth.js
- BE/package-lock.json
- BE/package.json
- BE/routers/auth.js
đã hoàn thành api forgot password send to email
refs:DTNF-99
> feat:create-api-forget-password-send-to-email

- BE/.env
- BE/modules/Auth/service/Auth.js
- FE/src/app/api/auth/auth.api.ts
- FE/src/app/modules/client/accountLogin/forgotPassword.component.tsx
- FE/src/app/modules/client/utils/validateForm.ts
đã hoàn thành chức năng forgotten password function refs:DTNF-100
> style:fe-as-forgotten-password-function

- BE/modules/Order/service/orderService.js
- BE/modules/Product/Service/Product.js
- FE/package-lock.json
- FE/package.json
- FE/src/app/container/defaul-admin/defaul-admin.component.tsx
- FE/src/app/modules/admin/category/category.component.tsx
- FE/src/app/modules/admin/common/template-table/template-table.component.tsx
- FE/src/app/modules/admin/order/order.component.tsx
- FE/src/app/modules/admin/order/service/order.service.tsx
- FE/src/app/modules/admin/product/product.component.tsx
- FE/src/app/modules/admin/user/user.component.tsx
- FE/src/app/modules/admin/vocher/vorcher.component.tsx
đã làm xong function order directly
refs:DTNF-107
> feat: create function order directly

- BE/modules/Auth/Controller/Api/updateUser.js
- FE/src/app/api/auth/auth.api.ts
- FE/src/app/modules/client/manager-info-customer/component/updatePassword.component.tsx
- FE/src/app/modules/client/manager-info-customer/manage-info-customer.component.tsx
- FE/src/app/modules/client/utils/validateForm.ts
Hoàn thành function user changes password
refs: DTNF-108
> feat: fe function user changes password

- BE/modules/Statistics/controller/api/index.js
- BE/modules/Statistics/controller/api/statistics-money.controller.js
- BE/modules/Statistics/controller/api/statistics.controller.js
- BE/modules/Statistics/controller/index.js
- BE/modules/Statistics/service/statistics.service.js
- BE/routers/statistics.js
- FE/package-lock.json
- FE/package.json
- FE/src/app/modules/admin/order/order.component.tsx
- FE/src/app/modules/admin/statistics/service/statistics.service.ts
- FE/src/app/modules/admin/statistics/statistics.component.tsx
- FE/src/app/modules/client/checkout/component/shipping/shipping.component.tsx
đã fix xong bug statistics totalprice
> bug: fix bug statistics totalprice

- FE/src/app/modules/admin/statistics/statistics.component.tsx
đã fix xong  bug statistics product
> bug:fix bug statistics product

- BE/modules/Comment_evaluate/Controller/api/createComment_evaluate.controller.js
- BE/modules/Comment_evaluate/Controller/api/deleteComment_evaluate.controller.js
- BE/modules/Comment_evaluate/Controller/api/getAllComment_evaluate.controller.js
- BE/modules/Comment_evaluate/Controller/api/getComment_evaluate.controller.js
- BE/modules/Comment_evaluate/Controller/api/updateComment_evaluate.controller.js
- BE/modules/Comment_evaluate/Controller/index.js
- BE/modules/Comment_evaluate/Model/comment_evaluate.model.js
- BE/modules/Comment_evaluate/Service/comment_evaluate.service.js
- BE/routers/comment_evaluate.js
- BE/routers/router.js
- FE/src/app/api/comment/comment.api.ts
- FE/src/app/component/parts/button/Button.componet.tsx
- FE/src/app/component/parts/review/review.component.tsx
- FE/src/app/component/parts/star/star.component.tsx
- FE/src/app/modules/admin/comment-admin/comment-admin.component.tsx
- FE/src/app/modules/admin/comment-admin/service/comment-admi.service.tsx
- FE/src/app/modules/admin/constance/menu-dashboard.tsx
- FE/src/app/modules/admin/router.tsx
- FE/src/app/modules/client/detail/main-detail/components/comment-evaluate/comment-evaluate.component.tsx
- FE/src/app/modules/client/detail/main-detail/main-detail.component.tsx
- FE/src/app/modules/client/redux/hook/useCommentReducer.ts
- FE/src/app/modules/client/redux/reducer/comment/commentSlice.ts
- FE/src/app/modules/client/redux/reducer/comment/thunk/commentThunk.ts
- FE/src/app/modules/client/redux/reducer/index.ts
Hoàn thành create-funtion-comments-and-reviews
refs:DTNF-112
> feat:create-funtion-comments-and-reviews

- BE/modules/Order/Model/Order.js
- BE/modules/Order/controller/api/filterOrderByStatus.js
- BE/modules/Order/controller/api/updateOrder.js
- BE/modules/Order/controller/index.js
- BE/modules/Order/service/orderService.js
- BE/routers/order.js
- FE/src/app/api/order/order.api.ts
- FE/src/app/modules/admin/common/component-order/table-order-detail.component.tsx
- FE/src/app/modules/admin/common/template-modal/template-modal.component.tsx
- FE/src/app/modules/admin/order/order.component.tsx
- FE/src/app/modules/admin/order/service/order.service.tsx
- FE/src/app/modules/admin/product/product.component.tsx
- FE/src/app/modules/admin/statistics/statistics.component.tsx
- FE/src/app/modules/client/manage-order/component/main-manage-order/main-manage-order.component.tsx
đã fix xong statictisc product and status order admin
> bug:fix statictisc product and status order admin

- FE/src/app/modules/admin/common/template-table/template-table.component.tsx
- FE/src/app/modules/client/products/products.component.tsx
- FE/src/app/modules/client/products/sidebarProducts/sidebarProducts.component.tsx
đã fix xong Latest product arrangement
>  bug: fixbug Latest product arrangement

- BE/modules/Comment_evaluate/Controller/api/createComment_evaluate.controller.js
- BE/modules/Comment_evaluate/Model/comment_evaluate.model.js
- BE/modules/Comment_evaluate/Service/comment_evaluate.service.js
- BE/routers/comment_evaluate.js
- FE/src/app/api/comment/comment.api.ts
- FE/src/app/component/parts/review/review.component.tsx
- FE/src/app/modules/admin/comment-admin/comment-admin.component.tsx
- FE/src/app/modules/admin/comment-admin/service/comment-admi.service.tsx
- FE/src/app/modules/admin/constance/menu-dashboard.tsx
- FE/src/app/modules/client/contact/contact.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/comment-evaluate/comment-evaluate.component.tsx
- FE/src/app/modules/client/manager-info-customer/manage-info-customer.component.tsx
- FE/src/app/modules/client/redux/hook/useCommentReducer.ts
- FE/src/app/modules/client/redux/reducer/comment/commentSlice.ts
Đã fix xong crud comment review
> bug: figbug crud comment review

- FE/src/app/container/defaul-admin/defaul-admin.component.tsx
- FE/src/app/modules/admin/common/template-table/template-table.component.tsx
- FE/src/app/modules/client/checkout/checkout.component.tsx
- FE/src/app/modules/client/manage-order/component/main-manage-order/main-manage-order.component.tsx
đã fix xong update order status
> bug: fixbug update order status

- FE/src/app/modules/admin/common/template-table/template-table.component.tsx
- FE/src/app/modules/admin/order/order.component.tsx
- FE/src/app/modules/admin/product/product.component.tsx
Tôi đã làm xong filter product admin
refs:DTNF-109
> feat:fe filter product admin

- BE/modules/Order/service/orderService.js
- BE/modules/Vorcher/model/Vorcher.js
- FE/src/app/modules/admin/common/component-order/table-order-detail.component.tsx
- FE/src/app/modules/admin/order/order.component.tsx
- FE/src/app/modules/admin/vocher/vorcher.component.tsx
- FE/src/app/modules/client/checkout/component/side-payment/AddVorcher/AddVorcher.component.tsx
- FE/src/app/modules/client/checkout/component/side-payment/AddVorcher/AddVorcherholiday.component.tsx
- FE/src/app/modules/client/checkout/component/side-payment/side-payment.component.tsx
Hoàn thành create function vorcher holiday
refs: DTNF-110
> feat: fe be create function vorcher holiday

- BE/modules/Comment_evaluate/Controller/api/createComment_evaluate.controller.js
- BE/modules/Comment_evaluate/Service/comment_evaluate.service.js
- FE/src/app/container/defaul-admin/defaul-admin.component.tsx
- FE/src/app/modules/admin/statistics/statistics.component.tsx
- FE/src/app/modules/client/checkout/component/side-payment/side-payment.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/comment-evaluate/comment-evaluate.component.tsx
- FE/src/app/modules/client/redux/reducer/cartSlice/cartSlice.ts
đã fix xong comment-review and statictis
> bug:fixbug comment-review and statictis

- FE/src/app/container/defaul-admin/defaul-admin.component.tsx
- FE/src/app/modules/admin/common/component-order/table-order-detail.component.tsx
- FE/src/app/modules/admin/constance/menu-dashboard.tsx
- FE/src/app/modules/admin/dashBoard/dashBoard.component.tsx
- FE/src/app/modules/admin/router.tsx
- FE/src/app/modules/admin/statistics/statistics.component.tsx
- FE/src/app/modules/client/error-customer/error-customer.component.tsx
- FE/src/app/modules/client/router.tsx
- FE/src/app/modules/client/thank-Customers/thankCustomers.component.tsx
Đã fix xong bug UI client and update UI logic Admin
> bug:fix bug UI client and update UI logic Admin

- BE/modules/payment/controller/getStatusPayment.controller.js
- FE/src/app/component/stack/header/header.component.tsx
- FE/src/app/modules/admin/common/component-order/table-order-detail.component.tsx
- FE/src/app/modules/admin/dashBoard/dashBoard.component.tsx
- FE/src/app/modules/admin/product/product.component.tsx
- FE/src/app/modules/admin/vocher/vorcher.component.tsx
đã fix xong  bug format price admin
> bug:fix bug format price admin

- BE/modules/Order/Model/Order.js
- BE/modules/Order/service/orderService.js
- FE/src/app/component/stack/header/header.component.tsx
- FE/src/app/component/stack/menu-sidebar/menu-sidebar.component.tsx
- FE/src/app/container/defaul-admin/defaul-admin.component.tsx
- FE/src/app/modules/admin/common/component-order/table-order-detail.component.tsx
- FE/src/app/modules/admin/product/product.component.tsx
- FE/src/app/modules/client/checkout/checkout.component.tsx
- FE/src/app/modules/client/checkout/component/payments/payments.componet.tsx
- FE/src/app/modules/client/manage-order/component/main-manage-order/main-manage-order.component.tsx
- FE/src/app/modules/client/manage-order/manage-order.component.tsx
đã fix xong all UI and logic project
> bug:fix bug all UI and logic project

- BE/modules/Comment_evaluate/Controller/api/searchComment_evaluate.controller.js
- BE/modules/Comment_evaluate/Controller/index.js
- BE/modules/Comment_evaluate/Model/comment_evaluate.model.js
- BE/modules/Comment_evaluate/Service/comment_evaluate.service.js
- BE/routers/comment_evaluate.js
- FE/src/app/api/comment/comment.api.ts
- FE/src/app/modules/admin/comment-admin/comment-admin.component.tsx
- FE/src/app/modules/admin/comment-admin/service/comment-admi.service.tsx
- FE/src/app/modules/admin/common/template-table/template-table.component.tsx
- FE/src/app/modules/client/accountLogin/login.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/comment-evaluate/comment-evaluate.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/detail-information/detail.infomation.component.tsx
Đã fig xong bug comment evaluate admin and client
> bug: fig bug comment evaluate admin and client

- BE/modules/Order/controller/api/deleteOrder.js
- BE/modules/payment/controller/getStatusPayment.controller.js
- FE/src/app/api/order/order.api.ts
- FE/src/app/api/payment/payment.api.ts
- FE/src/app/modules/admin/order/order.component.tsx
- FE/src/app/modules/admin/statistics/statistics.component.tsx
- FE/src/app/modules/client/checkout/checkout.component.tsx
đã update xong  logic delete order admin
> bug:update logic delete order admin

- FE/src/app/component/stack/header/header.component.tsx
- FE/src/app/modules/admin/category/category.component.tsx
- FE/src/app/modules/admin/comment-admin/comment-admin.component.tsx
- FE/src/app/modules/admin/content/content.component.tsx
- FE/src/app/modules/admin/order/order.component.tsx
- FE/src/app/modules/admin/statistics/statistics.component.tsx
- FE/src/app/modules/admin/user/user.component.tsx
- FE/src/app/modules/admin/vocher/vorcher.component.tsx
- FE/src/app/modules/client/checkout/component/payments/payments.componet.tsx
- FE/src/app/modules/client/checkout/component/side-payment/side-payment.component.tsx
Đã fix xong  bug validate form vs UI
> bug: fix bug validate form vs UI

- BE/modules/Comment_evaluate/Service/comment_evaluate.service.js
- BE/modules/Content/Controller/Api/searchContent.js
- BE/modules/Content/Controller/index.js
- BE/modules/Content/Service/Content.js
- BE/modules/payment/service/payment.service.js
- BE/routers/content.js
- FE/src/app/component/stack/header/header.component.tsx
- FE/src/app/modules/admin/content/content.component.tsx
- FE/src/app/modules/admin/content/service/content.service.tsx
- FE/src/app/modules/client/checkout/component/shipping/shipping.component.tsx
- FE/src/app/modules/client/checkout/component/side-payment/side-payment.component.tsx
- FE/src/app/modules/client/contact/contact.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/comment-evaluate/comment-evaluate.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/detail-information/detail.infomation.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/list-seen-product/list-seen-product.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/list-similar-product/list-similar-product.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/product-address/product-address.component.tsx
- FE/src/app/modules/client/error-customer/error-customer.component.tsx
- FE/src/app/modules/client/manager-info-customer/component/updatePassword.component.tsx
- FE/src/app/modules/client/products/listProduct/listProducts.component.tsx
- FE/src/app/modules/client/thank-Customers/thankCustomers.component.tsx
đã làm xong api searchcontent vs logic searchadmin refs:DTNF-116
> feat:create api searchcontent vs logic searchadmin

- BE/modules/Product/Model/Product.js
- BE/modules/Product/Service/Product.js
- FE/src/app/component/parts/itemproduct/itemproduct.component.tsx
- FE/src/app/modules/admin/common/component-order/table-order-detail.component.tsx
- FE/src/app/modules/admin/product/product.component.tsx
- FE/src/app/modules/admin/product/service/product.service.ts
- FE/src/app/modules/client/cart/components/leftCart/leftCart.component.tsx
- FE/src/app/modules/client/checkout/component/side-payment/side-payment.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/detail-information/detail.infomation.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/preview-img/preview.img.component.tsx
- FE/src/app/modules/client/helper/tranform.data.ts
- FE/src/app/modules/client/products/listProduct/listProducts.component.tsx
Tôi đã làm xong crud product admin
refs: DTNF-94
> feat: crud product admin

- FE/src/app/modules/admin/category/category.component.tsx
- FE/src/app/modules/admin/comment-admin/comment-admin.component.tsx
- FE/src/app/modules/admin/common/component-order/table-order-detail.component.tsx
- FE/src/app/modules/admin/common/template-table/template-table.component.tsx
- FE/src/app/modules/admin/constance/menu-dashboard.tsx
- FE/src/app/modules/admin/content/content.component.tsx
- FE/src/app/modules/admin/order/order.component.tsx
- FE/src/app/modules/admin/payment/payment.component.tsx
- FE/src/app/modules/admin/product/product.component.tsx
- FE/src/app/modules/admin/support-admin/support-admin.component.tsx
- FE/src/app/modules/admin/user/user.component.tsx
- FE/src/app/modules/admin/vocher/vorcher.component.tsx
Tôi đã fix xong logic upload image and fix validate form
> bug: update logic upload image and fix validate form

- BE/modules/Comment_evaluate/Controller/api/createComment_evaluate.controller.js
- BE/modules/Comment_evaluate/Model/comment_evaluate.model.js
- FE/src/app/component/parts/button/Button.componet.tsx
- FE/src/app/component/stack/header/header.component.tsx
- FE/src/app/modules/client/checkout/component/side-payment/side-payment.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/comment-evaluate/comment-evaluate.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/detail-information/detail.infomation.component.tsx
> bug: fix bug vorcher

- BE/modules/Product/Model/Product.js
- BE/modules/Product/Service/Product.js
- FE/src/app/modules/admin/order/order.component.tsx
- FE/src/app/modules/admin/product/product.component.tsx
- FE/src/app/modules/admin/user/user.component.tsx
- FE/src/app/modules/admin/vocher/vorcher.component.tsx
- FE/src/app/modules/client/manager-info-customer/manage-info-customer.component.tsx
Tôi đã fix xong bug logic admin
> bug:fix bug all logic admin

- FE/package-lock.json
- FE/package.json
- FE/src/app/modules/admin/category/category.component.tsx
- FE/src/app/modules/admin/user/user.component.tsx
- FE/src/app/modules/admin/vocher/vorcher.component.tsx
- FE/src/app/modules/client/detail/detail.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/list-seen-product/list-seen-product.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/list-similar-product/list-similar-product.component.tsx
- FE/src/app/modules/client/products/products.component.tsx
- FE/src/app/modules/client/utils/validateForm.ts
Tôi đã fix xong edit voucher and title admin
> bug:fix bug edit voucher and title admin

- BE/config/configVnpay.js
- BE/modules/Statistics/service/statistics.service.js
- FE/src/app/modules/admin/statistics/statistics.component.tsx
tôi đã fix xong bug statictis money
> bug:fixbug statictis money

- BE/config/connectDB.js
- FE/src/app/modules/admin/product/product.component.tsx
- FE/src/app/modules/admin/user/user.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/detail-information/detail.infomation.component.tsx
Tôi đã fix xong bug update date input user
> bug:fix bug update date input user

- FE/src/app/modules/admin/common/template-table/template-table.component.tsx
- FE/src/app/modules/admin/product/product.component.tsx
- FE/src/app/modules/client/products/listProduct/listProducts.component.tsx
- FE/src/app/modules/client/products/products.component.tsx
Tôi đã fix xong  bug edit product and loading product client
> bug: fix bug edit product and loading product client

- FE/package-lock.json
- FE/package.json
- FE/src/app/component/stack/header/header.component.tsx
- FE/src/app/modules/admin/comment-admin/comment-admin.component.tsx
- FE/src/app/modules/admin/common/template-table/template-table.component.tsx
- FE/src/app/modules/admin/order/order.component.tsx
- FE/src/app/modules/admin/user/user.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/list-seen-product/list-seen-product.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/list-similar-product/list-similar-product.component.tsx
- FE/src/app/modules/client/manager-info-customer/manage-info-customer.component.tsx
- FE/src/app/modules/client/utils/validateForm.ts
Tôi đã fix xong validate phone number và product similar
> bug:fix validate phone number and product similar

- BE/modules/Auth/Controller/Api/get-user-detail.js
- BE/modules/Auth/Controller/index.js
- BE/modules/Auth/service/Auth.js
- BE/routers/auth.js
- FE/src/App.tsx
- FE/src/app/api/auth/auth.api.ts
- FE/src/app/component/stack/footer/footer.component.tsx
- FE/src/app/component/stack/header/header.component.tsx
- FE/src/app/container/check-auth/CheckAdmin.component.tsx
- FE/src/app/container/check-auth/CheckAuth.component.tsx
- FE/src/app/container/defaul-admin/defaul-admin.component.tsx
- FE/src/app/modules/admin/router.tsx
- FE/src/app/modules/client/accountLogin/login.component.tsx
- FE/src/app/modules/client/checkout/checkout.component.tsx
- FE/src/app/modules/client/checkout/component/side-payment/side-payment.component.tsx
- FE/src/app/modules/client/products/products.component.tsx
Hoàn thành private admin user store, user
refs: DTNF-117
> feat: fe be check private admin user store, user

- BE/modules/Content/Controller/index.js
- BE/modules/Product/Controller/index.js
- FE/src/app/component/parts/itemproduct/itemproduct.component.tsx
- FE/src/app/component/parts/quantity/QuantityProduct.tsx
- FE/src/app/component/stack/header/header.component.tsx
- FE/src/app/container/default-home/default-home.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/comment-evaluate/comment-evaluate.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/detail-information/detail.infomation.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/list-seen-product/list-seen-product.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/list-similar-product/list-similar-product.component.tsx
- FE/src/app/modules/client/detail/main-detail/main-detail.component.tsx
- FE/src/app/modules/client/home/main-home/component/new-product/new-product.component.tsx
- FE/src/app/modules/client/home/main-home/component/sale-product/sale-product.component.tsx
- FE/src/app/modules/client/products/products.component.tsx
Tôi đã làm xong update ui client
> style: update ui client

- FE/src/app/component/parts/itemproduct/itemproduct.component.tsx
- FE/src/app/component/stack/header/header.component.tsx
- FE/src/app/modules/admin/category/category.component.tsx
- FE/src/app/modules/admin/comment-admin/comment-admin.component.tsx
- FE/src/app/modules/admin/common/component-order/table-order-detail.component.tsx
- FE/src/app/modules/admin/common/template-table/template-table.component.tsx
- FE/src/app/modules/admin/dashBoard/dashBoard.component.tsx
- FE/src/app/modules/admin/order/order.component.tsx
- FE/src/app/modules/admin/product/product.component.tsx
- FE/src/app/modules/admin/support-admin/support-admin.component.tsx
- FE/src/app/modules/admin/user/user.component.tsx
- FE/src/app/modules/admin/vocher/vorcher.component.tsx
- FE/src/app/modules/client/cart/components/leftCart/leftCart.component.tsx
- FE/src/app/modules/client/manage-order/component/main-manage-order/main-manage-order.component.tsx
- FE/src/app/modules/client/products/listProduct/listProducts.component.tsx
Tôi đã fix xong bug all project
> bug: fix bug all logic project

- FE/src/app/modules/client/products/listProduct/listProducts.component.tsx
- FE/src/app/modules/client/products/products.component.tsx
- FE/src/app/modules/client/products/sidebarProducts/sidebarProducts.component.tsx
tôi đã làm xong create-function-filter-size-and-color refs: DTNF-111
> feat:fe-create-function-filter-size-and-color

- BE/modules/Statistics/service/statistics.service.js
- FE/src/app/component/stack/header/header.component.tsx
- FE/src/app/modules/admin/order/order.component.tsx
- FE/src/app/modules/admin/statistics/statistics.component.tsx
- FE/src/app/modules/client/manage-order/component/main-manage-order/main-manage-order.component.tsx
tôi đã fix xong bug update orde
> bug: fixbug update order

- BE/modules/Order/service/orderService.js
- FE/src/app/modules/admin/order/order.component.tsx
Tôi đã update xong logic search order
> feat:update search order

- BE/modules/Category/Model/Category.js
- BE/modules/Category/Service/Category.js
- FE/src/app/modules/admin/category/category.component.tsx
- FE/src/app/modules/admin/common/template-table/template-table.component.tsx
- FE/src/app/modules/admin/product/product.component.tsx
- FE/src/app/modules/client/products/listProduct/listProducts.component.tsx
- FE/src/app/modules/client/products/sidebarProducts/sidebarProducts.component.tsx
tôi đã làm xong fix bug logic delete category
> bug: fix bug logic delete category

- FE/src/app/modules/admin/common/component-order/table-order-detail.component.tsx
- FE/src/app/modules/admin/constance/menu-dashboard.tsx
- FE/src/app/modules/admin/order/order.component.tsx
tôi đã làm xong show customer data when order directly refs:DTNF-118
> feat:show customer data when order directly

- FE/src/app/modules/admin/statistics/statistics.component.tsx
> bug:fixbug statictis

- FE/src/app/modules/admin/category/category.component.tsx
- FE/src/app/modules/admin/common/template-table/template-table.component.tsx
Tôi đã fix xong logic delete category
> bug:update logic delete category

- FE/src/app/modules/admin/statistics/statistics.component.tsx
- FE/src/app/modules/client/cart/cart.component.tsx
- FE/src/app/modules/client/cart/components/leftCart/leftCart.component.tsx
tôi đã update and fixbug xong statistic admin
> bug: update and fixbug statistic admin

- FE/src/app/component/parts/itemproduct/itemproduct.component.tsx
- FE/src/app/component/stack/footer/footer.component.tsx
- FE/src/app/component/stack/header/header.component.tsx
- FE/src/app/container/default-home/default-home.component.tsx
- FE/src/app/modules/client/home/main-home/component/new-product/new-product.component.tsx
- FE/src/app/modules/client/home/main-home/component/sale-product/sale-product.component.tsx
- FE/src/app/modules/client/home/main-home/component/slice/slice.component.tsx
- FE/src/app/modules/client/home/main-home/component/truth-value/truth-value.component.tsx
- FE/src/app/modules/client/home/main-home/main-home.component.tsx
- FE/src/app/modules/client/products/listProduct/listProducts.component.tsx
- FE/src/app/modules/client/products/products.component.tsx
- FE/src/app/modules/client/products/sidebarProducts/sidebarProducts.component.tsx
- FE/src/app/modules/client/products/titleProducts/titleProducts.component.tsx
Tôi đã làm xong  responsive home page and product page
> style: responsive home page and product page

- FE/src/app/component/stack/footer/footer.component.tsx
- FE/src/app/component/stack/header/header.component.tsx
- FE/src/app/container/defaul-admin/defaul-admin.component.tsx
- FE/src/app/modules/client/products/listProduct/listProducts.component.tsx
tôi đã fix xong bug search product page
> bug:fix bug search product page

- FE/src/app/modules/admin/common/template-modal/template-modal.component.tsx
- FE/src/app/modules/admin/order/order.component.tsx
tôi đã fix xong  logic order admin
> bug:update logic order admin

- BE/modules/Statistics/service/statistics.service.js
- FE/package-lock.json
- FE/package.json
- FE/src/app/container/defaul-admin/defaul-admin.component.tsx
- FE/src/app/modules/admin/statistics/statistics.component.tsx
đã làm xong statistics voucher method payment
refs:DTNF-123
> feat: create statistics voucher method payment

- BE/modules/Order/service/orderService.js
- FE/src/app/modules/admin/statistics/statistics.component.tsx
- FE/src/app/modules/client/checkout/checkout.component.tsx
tôi đã làm xong  add statistics gender
> feat: create add statistics gender

- BE/modules/Product/Model/Product.js
- FE/src/app/modules/admin/common/template-table/template-table.component.tsx
- FE/src/app/modules/admin/product/product.component.tsx
- FE/src/app/modules/admin/statistics/statistics.component.tsx
- FE/src/app/modules/client/redux/reducer/productSlice/productSlice.ts
Tôi đã fix xong filter sort by   product page and soft delete in admin
refs:DTNF-119
> feat:fix filter sort by   product page and soft delete in admin

- BE/modules/Auth/Model/Auth.js
- BE/modules/Order/service/orderService.js
- FE/src/app/component/stack/header/header.component.tsx
- FE/src/app/modules/admin/common/template-table/template-table.component.tsx
- FE/src/app/modules/admin/user/user.component.tsx
- FE/src/app/modules/client/cart/components/leftCart/leftCart.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/detail-information/detail.infomation.component.tsx
- FE/src/app/modules/client/orderProcess/orderProcess.component.tsx
- FE/src/app/modules/client/products/listProduct/listProducts.component.tsx
- FE/src/app/modules/client/products/products.component.tsx
- FE/src/app/modules/client/products/sidebarProducts/sidebarProducts.component.tsx
- FE/src/app/modules/client/redux/hook/useOrderReducer.ts
- FE/src/app/modules/client/redux/reducer/cartSlice/cartSlice.ts
- FE/src/app/modules/client/redux/reducer/orderSlice/orderSlice.ts
- FE/src/app/modules/client/redux/reducer/orderSlice/thunk/order.thunk.ts
- FE/src/app/modules/client/router.tsx
tôi đã fix xong bug manage order no user
> bug:fix bug manage order no user

- FE/src/app/component/stack/footer/footer.component.tsx
- FE/src/app/component/stack/header/header.component.tsx
- FE/src/app/modules/admin/category/category.component.tsx
- FE/src/app/modules/admin/order/order.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/comment-evaluate/comment-evaluate.component.tsx
> Bug: update order

- BE/modules/Cart/Controller/Api/addCart.js
- BE/modules/Category/Service/Category.js
- BE/modules/Comment_evaluate/Controller/api/createComment_evaluate.controller.js
- BE/modules/Order/controller/api/deleteOrder.js
- BE/modules/Order/controller/api/updateOrder.js
- FE/src/app/component/parts/quantity/quantitySelect.tsx
- FE/src/app/modules/admin/common/component-order/table-order-detail.component.tsx
- FE/src/app/modules/admin/common/template-table/template-table.component.tsx
- FE/src/app/modules/admin/order/order.component.tsx
- FE/src/app/modules/client/accountLogin/register.component.tsx
- FE/src/app/modules/client/cart/components/leftCart/leftCart.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/detail-information/detail.infomation.component.tsx
- FE/src/app/modules/client/orderProcess/orderProcess.component.tsx
- FE/src/app/modules/client/products/sidebarProducts/sidebarProducts.component.tsx
- FE/src/app/modules/client/redux/reducer/cartSlice/cartSlice.ts
t đã update xong manege order no acount
> bug: update manege order no acount

- BE/modules/Vorcher/model/Vorcher.js
- FE/src/app/component/stack/header/header.component.tsx
- FE/src/app/modules/admin/common/template-table/template-table.component.tsx
- FE/src/app/modules/admin/user/user.component.tsx
- FE/src/app/modules/client/accountLogin/login.component.tsx
- FE/src/app/modules/client/cart/cart.component.tsx
- FE/src/app/modules/client/cart/components/leftCart/leftCart.component.tsx
- FE/src/app/modules/client/orderProcess/orderProcess.component.tsx
- FE/src/app/modules/client/redux/reducer/cartSlice/cartSlice.ts
tôi đã fix xong bug add to cart
> bug:fix bug add to cart

- BE/.env
- BE/config/connectDB.js
- BE/modules/Order/Model/Order.js
- BE/modules/payment/controller/getStatusPayment.controller.js
- FE/src/app/component/stack/header/header.component.tsx
- FE/src/app/container/defaul-admin/defaul-admin.component.tsx
- FE/src/app/modules/admin/common/component-order/table-order-detail.component.tsx
- FE/src/app/modules/admin/constance/menu-dashboard.tsx
- FE/src/app/modules/admin/order/order.component.tsx
- FE/src/app/modules/client/checkout/checkout.component.tsx
- FE/src/app/modules/client/checkout/component/side-payment/side-payment.component.tsx
- FE/src/app/modules/client/detail/main-detail/components/detail-information/detail.infomation.component.tsx
- FE/src/app/modules/client/orderProcess/orderProcess.component.tsx
> bug: fix gub project
